services:
  - type: web
    name: text-summarization-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader -d /opt/render/project/src/.venv/nltk_data punkt punkt_tab
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
